### PR TITLE
Update to GitBucket 4.3

### PR DESCRIPTION
**Pull request by kosli**
- New UI based on AdminLTE
- git gc
- Issues and Wiki have been possible to be disabled
- SMTP configuration test mail

### CODE REVIEW

**Comment by f99aq8ove** [comment]
I'm waiting next version because of this issue.
https://github.com/gitbucket/gitbucket/issues/1231

**Comment by kosli** [comment]
thanks, haven't seen that one. okay let's wait for a fix.

**Comment by kosli** [comment]
Is the version 4.3 okay for an update?

**Comment by f99aq8ove** [comment]
Looks good. Thanks!

**Pull request merged**
